# Generated by Django 5.0.1 on 2024-04-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_recipe_delete_receipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_description',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_image',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_name',
            new_name='recipe_name',
        ),
    ]
